names = set()
names.add("Abhishek")
names.add("Bunty")
names.add("Manan")
names.add("Rohit")
names.add("Nidhi")
print(names)
names = set(((" ".join(names)).replace("Abhishek","AbhishekRoka")).split(" "))
print(names)
names.discard("Rohit")
names.discard("Nidhi")
print(names)